// Task 10 — Python WFS Service
// Task 11 — 矢量瓦片 (MVT) + 栅格瓦片 (XYZ/PNG)

import TileLayer from 'ol/layer/Tile';
import VectorLayer from 'ol/layer/Vector';
import VectorTileLayer from 'ol/layer/VectorTile';
import VectorSource from 'ol/source/Vector';
import VectorTileSource from 'ol/source/VectorTile';
import XYZ from 'ol/source/XYZ';
import GeoJSONFormat from 'ol/format/GeoJSON';
import MVT from 'ol/format/MVT';
import { bbox as bboxStrategy } from 'ol/loadingstrategy';
import { Style, Fill, Stroke, Circle as CircleStyle, Text } from 'ol/style';
import { fromLonLat } from 'ol/proj';

// ── Task 10: Python WFS layer ─────────────────────────────────────────────
// Proxy: /python-wfs → http://localhost:5000/wfs  (via vite.config.js)
const pythonWfsSource = new VectorSource({
    format: new GeoJSONFormat({ dataProjection: 'EPSG:3857', featureProjection: 'EPSG:3857' }),
    url: (extent) =>
        `/python-wfs?SERVICE=WFS&version=1.1.0&REQUEST=GetFeature` +
        `&typeName=xian&outputFormat=application/json` +
        `&srsname=EPSG:3857&bbox=${extent.join(',')},EPSG:3857`,
    strategy: bboxStrategy
});

export const pythonWfsLayer = new VectorLayer({
    source: pythonWfsSource,
    style: (feature) => {
        return new Style({
            stroke: new Stroke({ color: '#22c55e', width: 1.5 }),
            fill:   new Fill({ color: 'rgba(34,197,94,0.12)' })
        });
    },
    visible: false,
    zIndex: 85
});

// ── Task 11: 栅格瓦片 (PNG) ────────────────────────────────────────────────
// Pre-generated by generate_tiles.py → public/tiles/raster/{z}/{x}/{y}.png
// Covers zoom 3-4 (generated by Python script; extend with higher zooms if needed)
export const rasterTileLayer = new TileLayer({
    source: new XYZ({
        url: '/tiles/raster/{z}/{x}/{y}.png',
        minZoom: 3,
        maxZoom: 4,
        crossOrigin: 'anonymous'
    }),
    visible: false,
    zIndex: 82,
    opacity: 0.9
});

// ── Task 11: 矢量瓦片 (MVT/PBF) ───────────────────────────────────────────
// Generated by GDAL ogr2ogr → public/tiles/vector_gdal/{z}/{x}/{y}.pbf
// Covers zoom 3-8, layer name "xian"
export const vectorTileLayer = new VectorTileLayer({
    source: new VectorTileSource({
        format: new MVT(),
        url: '/tiles/vector_gdal/{z}/{x}/{y}.pbf',
        minZoom: 3,
        maxZoom: 8,
        attributions: 'GDAL MVT'
    }),
    style: new Style({
        stroke: new Stroke({ color: '#818cf8', width: 1 }),
        fill:   new Fill({ color: 'rgba(99,102,241,0.15)' })
    }),
    visible: false,
    zIndex: 83
});


// ── UI controller ─────────────────────────────────────────────────────────
export function initTasks1011(map) {
    map.addLayer(pythonWfsLayer);
    map.addLayer(rasterTileLayer);
    map.addLayer(vectorTileLayer);

    // ── Task 10 button handlers ───────────────────────────────────────────
    window.togglePythonWfs = (btn) => {
        const visible = !pythonWfsLayer.getVisible();
        pythonWfsLayer.setVisible(visible);
        btn.classList.toggle('active', visible);

        if (visible) {
            setStatus10('WFS 正在按视图范围请求要素…', 'loading');
            pythonWfsSource.clear();
            pythonWfsSource.once('featuresloadend', () => {
                const n = pythonWfsSource.getFeatures().length;
                setStatus10(`✓ Python WFS 已加载 ${n} 个要素`,'ok');
            });
            pythonWfsSource.once('featuresloaderror', () => {
                setStatus10('✗ 连接失败，请先运行 python wfs_server.py', 'err');
            });
            const ext = map.getView().calculateExtent(map.getSize());
            pythonWfsSource.loadFeatures(ext, map.getView().getResolution(), map.getView().getProjection());
        } else {
            pythonWfsSource.clear();
            setStatus10('WFS 图层已关闭');
        }
    };

    // ── Task 11 button handlers ───────────────────────────────────────────
    window.toggleRasterTile = (btn) => {
        const visible = !rasterTileLayer.getVisible();
        rasterTileLayer.setVisible(visible);
        btn.classList.toggle('active', visible);
        setStatus11(visible ? '栅格瓦片已激活' : '栅格瓦片已关闭');
        if (visible) flyToChina(map);
    };

    window.toggleVectorTile = (btn) => {
        const visible = !vectorTileLayer.getVisible();
        vectorTileLayer.setVisible(visible);
        btn.classList.toggle('active', visible);
        setStatus11(visible ? '矢量瓦片已激活' : '矢量瓦片已关闭');
        if (visible) flyToChina(map);
    };
}

function flyToChina(map) {
    map.getView().animate({
        center: fromLonLat([104.0, 35.5]),
        zoom: 4,
        duration: 600
    });
}

function setStatus10(msg, type = '') {
    const el = document.getElementById('python-wfs-status');
    if (!el) return;
    el.textContent = msg;
    el.className = 'status-msg' + (type ? ' ' + type : '');
}

function setStatus11(msg) {
    const el = document.getElementById('tile-status');
    if (el) el.textContent = msg;
}
